"""empty message

Revision ID: 1081400555ad
Revises: 49933a352ef
Create Date: 2017-06-21 12:56:57.337586

"""

# revision identifiers, used by Alembic.
revision = '1081400555ad'
down_revision = '49933a352ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(""" UPDATE resource SET meta_data = '{}'::json WHERE meta_data IS NULL; """)
    op.execute(""" UPDATE resource SET meta_data = CAST(concat('{"default_res_id":', meta_data ->> 'default_res_id', ', "is_deleted": false', '}') AS json) WHERE CAST(meta_data ->> 'default_res_id' AS integer) is not null; """)
    op.alter_column('resource', 'meta_data',
                    existing_type=postgresql.JSON(),
                    nullable=False,
                    existing_server_default=sa.text(u"'{}'::json"))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'meta_data',
                    existing_type=postgresql.JSON(),
                    nullable=True,
                    existing_server_default=sa.text(u"'{}'::json"))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
