import sqlalchemy as sa
from alembic import op
"""empty message

Revision ID: 10ac5264ca9d
Revises: 35f46d125cc8
Create Date: 2019-03-30 07:36:39.536165

"""

# revision identifiers, used by Alembic.
revision = '10ac5264ca9d'
down_revision = '35f46d125cc8'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column(
        'idp_usertype', sa.Unicode(), nullable=True))
    op.add_column('user_groups', sa.Column(
        'idp_usertype', sa.Unicode(), nullable=True))
    op.add_column('user_groups', sa.Column(
        'group_code', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'group_code')
    op.drop_column('user_groups', 'idp_usertype')
    op.drop_column('tenant', 'idp_usertype')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
