"""empty message

Revision ID: 13270820414c
Revises: 4c9acf112f39
Create Date: 2017-03-17 12:49:51.740583

"""

# revision identifiers, used by Alembic.
revision = '13270820414c'
down_revision = '4c9acf112f39'
branch_labels = None
depends_on = None

from datetime import datetime

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_reports():
    pass


def downgrade_reports():
    pass


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_language',
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], )
    )

    conn = op.get_bind()
    query = conn.execute("select * from languages where id='en_US'")
    language = query.fetchone()
    if not language:
        conn.execute("insert into languages(id, name, created_at, modified_at) values('en_US', 'English', '" + str(datetime.now()) + "','" + str(datetime.now()) + "')")

    op.add_column(u'tenant', sa.Column('default_locale_id', sa.Unicode(), nullable=False, server_default=u'en_US'))
    op.create_foreign_key('tenant_default_locale_id_fkey', 'tenant', 'languages', ['default_locale_id'], ['id'])

    conn.execute("update tenant set default_locale_id = language.id from Languages as language where language.id='en_US'")
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenant_default_locale_id_fkey', 'tenant', type_='foreignkey')
    op.drop_column(u'tenant', 'default_locale_id')
    op.drop_table('tenant_language')
    ### end Alembic commands ###
