"""empty message

Revision ID: 1620c33cf97
Revises: 8be28a074e7
Create Date: 2016-10-05 11:47:25.526801

"""

# revision identifiers, used by Alembic.
revision = '1620c33cf97'
down_revision = '8be28a074e7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('sections_users', 'sections_restricted_users')
    op.add_column('sections_restricted_users', sa.Column('is_granted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('sections_restricted_users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sections_restricted_users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('sections_restricted_users', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('sections_restricted_users', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key('sections_restricted_users_created_by_fkey', 'sections_restricted_users', 'users', ['created_by'], ['id'])
    op.create_foreign_key('sections_restricted_users_modified_by_fkey', 'sections_restricted_users', 'users', ['modified_by'], ['id'])
    op.drop_constraint(u'activity_feed_user_id_fkey', 'activity_feed', type_='foreignkey')
    op.alter_column('activity_feed', 'user_id', new_column_name='primary_user_id')
    op.add_column('activity_feed', sa.Column('secondary_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('activity_feed_primary_user_id_fkey', 'activity_feed', 'users', ['secondary_user_id'], ['id'])
    op.create_foreign_key('activity_feed_secondary_user_id_fkey', 'activity_feed', 'users', ['primary_user_id'], ['id'])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_feed_secondary_user_id_fkey', 'activity_feed', type_='foreignkey')
    op.drop_constraint('activity_feed_primary_user_id_fkey', 'activity_feed', type_='foreignkey')
    op.drop_column('activity_feed', 'secondary_user_id')
    op.alter_column('activity_feed', 'primary_user_id', new_column_name='user_id')
    op.create_foreign_key(u'activity_feed_user_id_fkey', 'activity_feed', 'users', ['user_id'], ['id'])
    op.drop_constraint('sections_restricted_users_modified_by_fkey', 'sections_restricted_users', type_='foreignkey')
    op.drop_constraint('sections_restricted_users_created_by_fkey', 'sections_restricted_users', type_='foreignkey')
    op.drop_column('sections_restricted_users', 'modified_by')
    op.drop_column('sections_restricted_users', 'modified_at')
    op.drop_column('sections_restricted_users', 'created_by')
    op.drop_column('sections_restricted_users', 'created_at')
    op.drop_column('sections_restricted_users', 'is_granted')
    op.rename_table('sections_restricted_users', 'sections_users')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
