"""empty message

Revision ID: 163280dc744e
Revises: 1316d35d9acc
Create Date: 2017-10-09 13:17:04.873881

"""

# revision identifiers, used by Alembic.
revision = '163280dc744e'
down_revision = 'c3e27c3e3e6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()

def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_option_translations', sa.Column('suggestion_message',  postgresql.JSON(), nullable=True, default=sa.text(u"'{}'::json")))
    op.execute('update draft_option_translations set suggestion_message = (select suggestion_message from draft_options where draft_options.id = draft_option_translations.option_id);')
    op.add_column('option_translations', sa.Column('suggestion_message', postgresql.JSON(), nullable=True, default=sa.text(u"'{}'::json")))
    op.execute('update option_translations set suggestion_message = (select suggestion_message from options where options.id = option_translations.option_id);')
    op.drop_column('draft_options', 'suggestion_message')
    op.drop_column('options', 'suggestion_message')
    op.rename_table('quiz_actitvity', 'quiz_activity')
    op.add_column('tenant', sa.Column('cdn_enable', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('resource', sa.Column('is_cdn_ready', sa.Boolean(),nullable = False, server_default = 'false'))
    op.add_column('icon_library', sa.Column('is_cdn_ready', sa.Boolean(),nullable = False, server_default = 'false'))

    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icon_library', 'is_cdn_ready')
    op.drop_column('resource', 'is_cdn_ready')
    op.drop_column('tenant', 'cdn_enable')
    op.rename_table('quiz_activity', 'quiz_actitvity')
    op.add_column('options', sa.Column('suggestion_message', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('option_translations', 'suggestion_message')
    op.add_column('draft_options', sa.Column('suggestion_message', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('draft_option_translations', 'suggestion_message')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

