"""empty message

Revision ID: 16a378b11b0b
Revises: 4d53f869526
Create Date: 2016-09-07 16:14:48.380860

"""

# revision identifiers, used by Alembic.
revision = '16a378b11b0b'
down_revision = '4d53f869526'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections_users',
                    sa.Column('section_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections_users')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
