"""empty message

Revision ID: 16af01d0ee71
Revises: 2c2355fabfe6
Create Date: 2015-08-19 15:19:00.774620

"""

# revision identifiers, used by Alembic.
revision = '16af01d0ee71'
down_revision = '2c2355fabfe6'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('campaign_tracking_code', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'campaign_tracking_code')
    ### end Alembic commands ###


def downgrade_reports():
    pass
