"""empty message

Revision ID: 173930a0a2b2
Revises: dacba323283
Create Date: 2016-04-20 21:51:23.303479

"""

# revision identifiers, used by Alembic.
revision = '173930a0a2b2'
down_revision = 'dacba323283'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('allow_offline', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenant', sa.Column('can_download', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenant', sa.Column('can_embed', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'can_embed')
    op.drop_column('tenant', 'can_download')
    op.drop_column('tenant', 'allow_offline')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
