"""empty message

Revision ID: 1766021659c9
Revises: 259fc108434
Create Date: 2017-09-08 04:34:44.321559

"""

# revision identifiers, used by Alembic.
revision = '1766021659c9'
down_revision = '259fc108434'
branch_labels = None
depends_on = None

from alembic import op


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.create_unique_constraint('uq_tenant_domain', 'tenant', ['domain'])
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_constraint('uq_tenant_domain', 'tenant', type_='unique')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
