"""empty message

Revision ID: 18933d866046
Revises: 397e0841ad63
Create Date: 2019-06-23 17:39:42.495705

"""

# revision identifiers, used by Alembic.
revision = '18933d866046'
down_revision = '3f86eb555b5e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'draft_journeys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.Unicode(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('cta_id', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['cta_id'], ['lead_cta_form.id'], ),
        sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'draft_journey_translations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(), nullable=False),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('journey_id', sa.Integer(), nullable=False),
        sa.Column('language_id', sa.Unicode(), nullable=False),
        sa.Column('icon_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], ),
        sa.ForeignKeyConstraint(['journey_id'], ['draft_journeys.id'], ),
        sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'draft_journey_user_group_association',
        sa.Column('journey_id', sa.Integer(), nullable=False),
        sa.Column('user_groups_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['journey_id'], ['draft_journeys.id'], ),
        sa.ForeignKeyConstraint(['user_groups_id'], ['user_groups.id'], ),
        sa.PrimaryKeyConstraint('journey_id', 'user_groups_id')
    )
    op.create_table(
        'draft_journey_assets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('asset_type', sa.Unicode(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('journey_id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['journey_id'], ['draft_journeys.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'journeys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.Unicode(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('draft_id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('cta_id', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['cta_id'], ['lead_cta_form.id'], ),
        sa.ForeignKeyConstraint(['draft_id'], ['draft_journeys.id'], ),
        sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'journey_translations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(), nullable=False),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('journey_id', sa.Integer(), nullable=False),
        sa.Column('language_id', sa.Unicode(), nullable=False),
        sa.Column('icon_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], ),
        sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
        sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'journey_user_group_association',
        sa.Column('journey_id', sa.Integer(), nullable=False),
        sa.Column('user_groups_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
        sa.ForeignKeyConstraint(['user_groups_id'], ['user_groups.id'], ),
        sa.PrimaryKeyConstraint('journey_id', 'user_groups_id')
    )
    op.create_table(
        'journey_assets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('asset_type', sa.Unicode(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('journey_id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_assets')
    op.drop_table('journey_user_group_association')
    op.drop_table('journey_translations')
    op.drop_table('journeys')
    op.drop_table('draft_journey_assets')
    op.drop_table('draft_journey_user_group_association')
    op.drop_table('draft_journey_translations')
    op.drop_table('draft_journeys')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
