"""empty message

Revision ID: 1bfe9dc0682d
Revises: e04df8bed24
Create Date: 2019-09-16 09:25:44.569916

"""

# revision identifiers, used by Alembic.
revision = '1bfe9dc0682d'
down_revision = 'e04df8bed24'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_bulletin_board_links_tenant_id', 'bulletin_board_links', 'tenant', ['tenant_id'], ['id'])
    op.add_column('draft_walkthrough', sa.Column('unique_id', sa.Unicode(), nullable=True))
    op.create_unique_constraint('uq_draft_walkthrough_unique_id', 'draft_walkthrough', ['unique_id'])
    op.add_column('walkthrough', sa.Column('unique_id', sa.Unicode(), nullable=True))
    op.create_unique_constraint('uq_walkthrough_unique_id', 'walkthrough', ['unique_id'])
    ### end Alembic commands ###

def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_walkthrough_unique_id', 'walkthrough', type_='unique')
    op.drop_column('walkthrough', 'unique_id')
    op.drop_constraint('uq_draft_walkthrough_unique_id', 'draft_walkthrough', type_='unique')
    op.drop_column('draft_walkthrough', 'unique_id')
    op.drop_constraint('fk_bulletin_board_links_tenant_id', 'bulletin_board_links', type_='foreignkey')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

