"""empty message

Revision ID: 1d832a6e8e61
Revises: 4300f53ff2f8
Create Date: 2019-02-11 10:26:19.813179

"""

# revision identifiers, used by Alembic.
revision = '1d832a6e8e61'
down_revision = '4300f53ff2f8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklist_draft_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('checklist_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('draft_path_translations', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('path_translations', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('faq_draft_group_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('faq_group_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('quiz_draft_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('quiz_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('quiz_draft_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('faq_group_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('faq_draft_group_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('path_translations', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('draft_path_translations', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('checklist_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('checklist_draft_translation', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
