"""empty message

Revision ID: 1d9b8b56469a
Revises: 55c7e1d9da2d
Create Date: 2015-03-06 07:11:29.428055

"""

# revision identifiers, used by Alembic.
revision = '1d9b8b56469a'
down_revision = '55c7e1d9da2d'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('product_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'product_id')
    ### end Alembic commands ###


def downgrade_reports():
    pass
