"""empty message

Revision ID: 1de0993ab050
Revises: 4d7f4a56ada6
Create Date: 2016-06-24 09:55:13.998152

"""

# revision identifiers, used by Alembic.
revision = '1de0993ab050'
down_revision = '4d7f4a56ada6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('tenant', sa.Column('crm_settings', postgresql.JSON(), nullable=True))
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('tenant', 'crm_settings')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
