"""empty message

Revision ID: 1e3fdb46f58f
Revises: 1e25e1094768
Create Date: 2015-01-12 09:49:48.314280

"""

# revision identifiers, used by Alembic.
revision = '1e3fdb46f58f'
down_revision = '1e25e1094768'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('background_color', sa.Unicode(), nullable=False),
    sa.Column('right_border_color', sa.Unicode(), nullable=False),
    sa.Column('right_border_color_hover', sa.Unicode(), nullable=False),
    sa.Column('left_border_color', sa.Unicode(), nullable=False),
    sa.Column('left_border_color_hover', sa.Unicode(), nullable=False),
    sa.Column('progress_bar_color', sa.Unicode(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'tenant', sa.Column('analytics', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tenant', 'analytics')
    op.drop_table('tenant_theme')
    ### end Alembic commands ###


def downgrade_reports():
    pass
