"""empty message

Revision ID: 1ec446c565cf
Revises: 1af7ba79c565
Create Date: 2016-10-03 15:57:47.793979

"""

# revision identifiers, used by Alembic.
revision = '1ec446c565cf'
down_revision = '1af7ba79c565'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_digest', sa.Column('show_leads', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail_digest', 'show_leads')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
