"""empty message

Revision ID: 1ed78ec8a766
Revises: 5aa8a2a385fd
Create Date: 2014-12-18 09:11:24.928455

"""

# revision identifiers, used by Alembic.
revision = '1ed78ec8a766'
down_revision = '5aa8a2a385fd'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completion_activity', sa.Column('product_id', sa.Integer(), nullable=True))
    op.alter_column('completion_activity', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('completion_activity', 'walkthrough_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('walkthrough_activity', sa.Column('product_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walkthrough_activity', 'product_id')
    op.alter_column('completion_activity', 'walkthrough_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('completion_activity', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('completion_activity', 'product_id')
    ### end Alembic commands ###


def downgrade_reports():
    pass
