"""empty message

Revision ID: 1f44f850630b
Revises: 27f916d97b29
Create Date: 2018-07-11 11:34:09.683700

"""

# revision identifiers, used by Alembic.
revision = '1f44f850630b'
down_revision = '27f916d97b29'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    op.execute(""" UPDATE section_translations SET tag_ids = NULL WHERE tag_ids::text in ('[]', '"[]"', '{}'); """)
    op.execute(""" ALTER TABLE section_translations ALTER tag_ids DROP DEFAULT; """)
    op.execute(""" ALTER TABLE section_translations
                   ALTER COLUMN tag_ids TYPE INTEGER[]
                   USING translate(tag_ids::text, '[]', '{}')::int[];
               """)


def downgrade_():
    op.execute(""" ALTER TABLE section_translations
                   ALTER COLUMN tag_ids TYPE JSON
                   USING to_json(tag_ids);
               """)


def upgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

