"""empty message

Revision ID: 2183b5640bf2
Revises: 25a95bf846db
Create Date: 2019-08-21 08:24:29.980473

"""

# revision identifiers, used by Alembic.
revision = '2183b5640bf2'
down_revision = '4215e4021438'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboard_at', sa.DateTime(), nullable=True))
    conn = op.get_bind()
    conn.execute("update users set onboard_at = created_at")
    ### end Alembic commands ###

def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboard_at')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
