"""empty message

Revision ID: 218d8fb2b7b3
Revises: 30e17500bac4
Create Date: 2020-02-27 11:40:55.607836

"""

# revision identifiers, used by Alembic.
revision = '218d8fb2b7b3'
down_revision = '30e17500bac4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    op.create_table(
        'section_journeys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('section_id', sa.Integer(), nullable=False),
        sa.Column('journey_id', sa.Integer(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
        sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade_():
    op.drop_table('section_journeys')


def upgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
