"""empty message

Revision ID: 229cfa5d5d5f
Revises: 51ad2a881595
Create Date: 2016-03-22 17:24:24.636351

"""

# revision identifiers, used by Alembic.
revision = '229cfa5d5d5f'
down_revision = '51ad2a881595'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('content', sa.Unicode(), nullable=True))
    op.add_column('resource', sa.Column('language_id', sa.Unicode(), nullable=False, server_default=u'en_US'))
    op.alter_column('resource', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('resource_language_id_fkey', 'resource', 'languages', ['language_id'], ['id'])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resource_language_id_fkey', 'resource', type_='foreignkey')
    op.execute(""" UPDATE resource SET path = '' WHERE path IS NULL """)
    op.alter_column('resource', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('resource', 'language_id')
    op.drop_column('resource', 'content')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
