from alembic import op
import sqlalchemy as sa

"""
Create Dowloads table.

Revision ID: 233158ceab66
Revises: 4137c03c4e18
Create Date: 2018-08-21 11:19:18.707113

"""

# revision identifiers, used by Alembic.
revision = '233158ceab66'
down_revision = '4137c03c4e18'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.create_table(
        'downloads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('entity_type', sa.Unicode(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('entity_name', sa.Unicode(), nullable=False),
        sa.Column('url', sa.Unicode(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user_activity.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_table('downloads')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
