"""empty message

Revision ID: 24391637c175
Revises: 267fc4a0d822
Create Date: 2015-07-30 22:48:45.516543

"""

# revision identifiers, used by Alembic.
revision = '24391637c175'
down_revision = '267fc4a0d822'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_leads', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('website_leads', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.execute("update website_leads set created_at='2015-07-30', modified_at='2015-07-30';")
    op.alter_column('website_leads', 'created_at', nullable=False)
    op.alter_column('website_leads', 'modified_at', nullable=False)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_leads', 'modified_at')
    op.drop_column('website_leads', 'created_at')
    ### end Alembic commands ###


def downgrade_reports():
    pass
