"""empty message

Revision ID: 249c3ea96873
Revises: 1081400555ad
Create Date: 2017-07-04 06:14:25.341405

"""

# revision identifiers, used by Alembic.
revision = '249c3ea96873'
down_revision = '1081400555ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.create_table(
        'suggestion_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('option_id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'suggestion_group_translations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Unicode(), nullable=False),
        sa.Column('description', sa.Unicode(), nullable=False),
        sa.Column('language_id', sa.Unicode(), nullable=False),
        sa.Column('suggestion_group_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
        sa.ForeignKeyConstraint(['suggestion_group_id'], ['suggestion_groups.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'suggestions', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column(
        u'suggestions', 'option_id',
        existing_type=sa.INTEGER(),
        nullable=False)
    op.create_foreign_key('suggestions_group_id_fkey', 'suggestions', 'suggestion_groups', ['group_id'], ['id'])
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_constraint('suggestions_group_id_fkey', 'suggestions', type_='foreignkey')
    op.alter_column(
        u'suggestions', 'option_id',
        existing_type=sa.INTEGER(),
        nullable=True)
    op.drop_column(u'suggestions', 'group_id')
    op.drop_table('suggestion_group_translations')
    op.drop_table('suggestion_groups')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
