"""empty message

Revision ID: 25312a814723
Revises: 3490c9baf802
Create Date: 2017-09-27 20:40:18.662506

"""

# revision identifiers, used by Alembic.
revision = '25312a814723'
down_revision = '3490c9baf802'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.execute(""" UPDATE quiz SET grading_style = 'marks' WHERE grading_style IS NULL """)
    op.alter_column(
        'quiz', 'grading_style',
        existing_type=sa.VARCHAR(),
        nullable=False)
    op.execute(""" UPDATE quiz_draft SET grading_style = 'marks' WHERE grading_style IS NULL """)
    op.alter_column(
        'quiz_draft', 'grading_style',
        existing_type=sa.VARCHAR(),
        nullable=False)
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column(
        'quiz_draft', 'grading_style',
        existing_type=sa.VARCHAR(),
        nullable=True)
    op.alter_column(
        'quiz', 'grading_style',
        existing_type=sa.VARCHAR(),
        nullable=True)
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
