"""empty message

Revision ID: 25d8a6172167
Revises: 4bfaff72f91b
Create Date: 2015-07-10 15:47:23.482788

"""

# revision identifiers, used by Alembic.
revision = '25d8a6172167'
down_revision = '4bfaff72f91b'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_user_id', sa.Unicode(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('picture_url', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unique_user_id')
    )
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_leads')
    ### end Alembic commands ###


def downgrade_reports():
    pass
