"""empty message

Revision ID: 266738c026ff
Revises: eecc38549f1
Create Date: 2015-01-29 06:35:11.626988

"""

# revision identifiers, used by Alembic.
revision = '266738c026ff'
down_revision = 'eecc38549f1'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('walkthrough', sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenant', sa.Column('logo', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walkthrough', 'is_enabled')
    op.drop_column('section', 'is_enabled')
    op.drop_column('tenant', 'logo')
    ### end Alembic commands ###


def downgrade_reports():
    pass
