"""empty message

Revision ID: 271fded6fa63
Revises: 37f4c009318f
Create Date: 2015-06-22 07:05:27.543111

"""

# revision identifiers, used by Alembic.
revision = '271fded6fa63'
down_revision = '37f4c009318f'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Unicode(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_digest_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('unsubscribe', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('mail_digest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mail_digest_id'], ['mail_digest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_digest_users')
    op.drop_table('mail_digest')
    ### end Alembic commands ###


def downgrade_reports():
    pass
