"""empty message

Revision ID: 29470f1c0ff1
Revises: 4c921b112426
Create Date: 2014-11-18 11:41:31.286227

"""

# revision identifiers, used by Alembic.
revision = '29470f1c0ff1'
down_revision = '4c921b112426'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('description', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'description')
    ### end Alembic commands ###


def downgrade_reports():
    pass
