"""empty message

Revision ID: 29a0c4f02d5f
Revises: 4e2c22c38d6a
Create Date: 2016-12-22 10:48:57.075176

"""

# revision identifiers, used by Alembic.
revision = '29a0c4f02d5f'
down_revision = '4e2c22c38d6a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.add_column('mail_digest', sa.Column('show_visitors', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    op.add_column('mail_digest', sa.Column('show_content_updates', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    bind.execute("update mail_digest set section_id = NULL where all_products = True")
    bind.execute("update mail_digest set show_visitors=True where show_leads=False and show_viewers=False")
    op.drop_column('mail_digest', 'all_products')
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_digest', sa.Column('all_products', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=True))
    op.drop_column('mail_digest', 'show_visitors')
    op.drop_column('mail_digest', 'show_content_updates')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
