from alembic import op
import sqlalchemy as sa

"""empty message

Revision ID: 2ad3e5a8eab3
Revises: 36d41082ef81
Create Date: 2019-04-07 06:43:17.956667

"""

# revision identifiers, used by Alembic.
revision = '2ad3e5a8eab3'
down_revision = '36d41082ef81'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column(
        'user_groups',
        sa.Column(
            'role_id',
            sa.Integer(),
            nullable=False,
            server_default='4'
        )
    )
    op.create_foreign_key(
        'user_groups_role_id_fkey',
        'user_groups',
        'role',
        ['role_id'],
        ['id']
    )
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_constraint(
        'user_groups_role_id_fkey',
        'user_groups',
        type_='foreignkey'
    )
    op.drop_column('user_groups', 'role_id')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
