"""empty message

Revision ID: 2b3e18f648c7
Revises: 29470f1c0ff1
Create Date: 2014-12-01 04:52:33.933822

"""

# revision identifiers, used by Alembic.
revision = '2b3e18f648c7'
down_revision = '29470f1c0ff1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_user_id', sa.Unicode(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('walkthrough_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.unique_user_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthrough.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'hotspot', sa.Column('callout', postgresql.JSON(), nullable=True))
    op.add_column(u'walkthrough_activity', sa.Column('duration', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'walkthrough_activity', 'duration')
    op.drop_column(u'hotspot', 'callout')
    op.drop_table('visit_activity')
    ### end Alembic commands ###


def downgrade_reports():
    pass
