"""empty message

Revision ID: 2c2355fabfe6
Revises: 47ca7d119706
Create Date: 2015-08-19 07:00:55.545878

"""

# revision identifiers, used by Alembic.
revision = '2c2355fabfe6'
down_revision = '47ca7d119706'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_theme', 'hover_border_color')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_theme', sa.Column('hover_border_color', sa.VARCHAR(), autoincrement=False, server_default='#fa575c', nullable=False))
    ### end Alembic commands ###


def downgrade_reports():
    pass
