"""empty message

Revision ID: 2c9a7981d8c
Revises: 38236fc333db
Create Date: 2016-03-04 14:24:26.325388

"""

# revision identifiers, used by Alembic.
revision = '2c9a7981d8c'
down_revision = '38236fc333db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='1',
               existing_server_default=sa.text(u'3'))
    op.add_column('users', sa.Column('registration_status', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_status')
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='3',
               existing_server_default=sa.text(u'1'))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
