"""empty message

Revision ID: 2d505cdb960e
Revises: ae85cef399
Create Date: 2015-02-03 11:18:20.300165

"""

# revision identifiers, used by Alembic.
revision = '2d505cdb960e'
down_revision = 'ae85cef399'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walkthrough', sa.Column('link_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walkthrough', 'link_id')
    ### end Alembic commands ###


def downgrade_reports():
    pass
