"""empty message

Revision ID: 2d72b8159c5c
Revises: 16bb997a2a79
Create Date: 2017-04-26 12:29:14.419757

"""

# revision identifiers, used by Alembic.
revision = '2d72b8159c5c'
down_revision = '16bb997a2a79'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.create_table(
        'options_chapters',
        sa.Column('option_id', sa.Integer(), nullable=False),
        sa.Column('walkthrough_id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthrough.id'], ),
        sa.PrimaryKeyConstraint('option_id', 'walkthrough_id', 'tenant_id')
    )
    op.drop_table('options_tags')
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.create_table(
        'options_tags',
        sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['option_id'], [u'options.id'], name=u'options_tags_option_id_fkey'),
        sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], name=u'options_tags_tag_id_fkey')
    )
    op.drop_table('options_chapters')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
