"""empty message

Revision ID: 2ddb217d2b1e
Revises: 4d0b7997372a
Create Date: 2014-10-06 16:57:37.844607

"""

# revision identifiers, used by Alembic.
revision = '2ddb217d2b1e'
down_revision = '4d0b7997372a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hotspot', 'action',
               existing_type=postgresql.JSON(),
               nullable=False)
    op.alter_column('hotspot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('hotspot', 'display',
               existing_type=postgresql.JSON(),
               nullable=False)
    op.alter_column('hotspot', 'hotspot_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hotspot', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('hotspot', 'slide_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resource', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('resource', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('resource', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resource', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resource', 'resource_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resource', 'walkthrough_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('section', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('section', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('section', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('section', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('section', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('slide', sa.Column('name', sa.Unicode(), nullable=False, server_default=u''))
    op.alter_column('slide', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('slide', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('slide', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('slide', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('slide', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('slide', 'walkthrough_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tag', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('walkthrough', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('walkthrough', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('walkthrough', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('walkthrough', 'resource_hostname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('walkthrough', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('walkthrough', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('walkthrough', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('walkthrough', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('walkthrough', 'resource_hostname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('walkthrough', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('walkthrough', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('walkthrough', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tag', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tag', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('slide', 'walkthrough_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('slide', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('slide', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('slide', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('slide', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('slide', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('slide', 'name')
    op.alter_column('section', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('section', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('section', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('section', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('section', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resource', 'walkthrough_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('resource', 'resource_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resource', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resource', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resource', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resource', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hotspot', 'slide_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hotspot', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hotspot', 'hotspot_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hotspot', 'display',
               existing_type=postgresql.JSON(),
               nullable=True)
    op.alter_column('hotspot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hotspot', 'action',
               existing_type=postgresql.JSON(),
               nullable=True)
    ### end Alembic commands ###


def downgrade_reports():
    pass
