"""empty message

Revision ID: 2e1d1ca5a9ac
Revises: 249c3ea96873
Create Date: 2017-07-11 13:21:07.340948

"""

# revision identifiers, used by Alembic.
revision = '2e1d1ca5a9ac'
down_revision = '249c3ea96873'
branch_labels = None
depends_on = None

from uuid import uuid4

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def generate_uuid():
    unique_id = unicode(uuid4()).replace('-', '')
    return unique_id


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('audience_companies', sa.Column('message', sa.Unicode(), nullable=False, server_default=""))
    op.add_column('audience_employees', sa.Column('email_sent', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('audience_employees', sa.Column('password', sa.Unicode(), nullable=True))
    op.add_column('audience_employees', sa.Column('unique_user_id', sa.Unicode(), nullable=True))

    conn = op.get_bind()
    users_list = conn.execute("select * from audience_employees").fetchall()
    for user in users_list:
        conn.execute("update audience_employees set unique_user_id='" + unicode(generate_uuid()) + "' where id=" + str(user.id))

    op.alter_column('audience_employees', 'unique_user_id',
                    existing_type=sa.Unicode(),
                    nullable=False)
    op.create_unique_constraint('audience_employees_unique_user_id_key', 'audience_employees', ['unique_user_id'])
    op.drop_column('audience_companies', 'is_share_whole_site')
    op.drop_column('audience_employees', 'picture_url')
    op.drop_column('audience_employees', 'is_admin_added')
    op.drop_column('audience_employees', 'designation')
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('audience_employees', sa.Column('designation', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('audience_employees', sa.Column('is_admin_added', sa.BOOLEAN(), autoincrement=False, nullable=False,
                                                  server_default="true"))
    op.add_column('audience_employees', sa.Column('picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audience_companies', sa.Column('is_share_whole_site', sa.BOOLEAN(), autoincrement=False, nullable=False,
                                                  server_default="false"))
    op.drop_constraint('audience_employees_unique_user_id_key', 'audience_employees', type_='unique')
    op.drop_column('audience_employees', 'unique_user_id')
    op.drop_column('audience_employees', 'password')
    op.drop_column('audience_employees', 'email_sent')
    op.drop_column('audience_companies', 'message')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
