"""empty message

Revision ID: 2ebb41db7701
Revises: 3eb85ca66889
Create Date: 2015-09-23 17:59:23.817043

"""

# revision identifiers, used by Alembic.
revision = '2ebb41db7701'
down_revision = '3eb85ca66889'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads_generated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('leads_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['report_tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('visitors', 'signups_count')
    ### end Alembic commands ###


def downgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads_generated')
    op.add_column('visitors', sa.Column('signups_count', sa.INTEGER(), server_default="0", autoincrement=False, nullable=False))
    ### end Alembic commands ###
