"""empty message

Revision ID: 2f53338a593a
Revises: 2ddb217d2b1e
Create Date: 2014-10-16 12:19:41.585087

"""

# revision identifiers, used by Alembic.
revision = '2f53338a593a'
down_revision = '2ddb217d2b1e'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide', sa.Column('av_resource_id', sa.Integer(), nullable=True))
    op.add_column('slide', sa.Column('image_resource_id', sa.Integer(), nullable=True))
    op.drop_column('slide', 'resource_id')

    op.create_foreign_key('slide_av_resource_id_fkey', 'slide', 'resource', ['av_resource_id'], ['id'])
    op.create_foreign_key('slide_image_resource_id_fkey', 'slide', 'resource', ['image_resource_id'], ['id'])
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide', sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('slide', 'image_resource_id')
    op.drop_column('slide', 'av_resource_id')

    op.create_foreign_key('slide_resource_id_fkey', 'slide', 'resource', ['resource_id'], ['id'])
    ### end Alembic commands ###


def downgrade_reports():
    pass
