"""empty message

Revision ID: 30a5922f7909
Revises: 1bfe9dc0682d
Create Date: 2019-08-19 11:09:29.535963

"""

# revision identifiers, used by Alembic.
revision = '30a5922f7909'
down_revision = '1bfe9dc0682d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entity_type', sa.Unicode(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.Unicode(), nullable=True),
        sa.Column('expire_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_type', 'entity_id', name='uq_entity_type_id'),
        sa.UniqueConstraint('job_id', name='uq_scheduler_job_id'),
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###`
    op.drop_table('scheduler')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass