from alembic import op
import sqlalchemy as sa

"""
Revision ID: 30ae701c85ae
Revises: 30c5f89b4074
Create Date: 2018-10-03 09:20:12.456332
"""

# revision identifiers, used by Alembic.
revision = '30ae701c85ae'
down_revision = '30c5f89b4074'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.create_table(
        'html_apps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(), nullable=False),
        sa.Column('slug', sa.Unicode(), nullable=True),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), server_default='false',
                  nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'slug',
                            name='uq_html_app_tenant_id_slug')
    )
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_table('html_apps')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
