"""empty message

Revision ID: 311b5149e5ed
Revises: 3ce5690d81ae
Create Date: 2020-01-12 18:36:14.450309

"""

# revision identifiers, used by Alembic.
revision = '311b5149e5ed'
down_revision = '3ce5690d81ae'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'draft_pitch_section', 'max_attempts',
        existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        'pitch_section', 'max_attempts',
        existing_type=sa.INTEGER(), nullable=True
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'pitch_section', 'max_attempts',
        existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        'draft_pitch_section', 'max_attempts',
        existing_type=sa.INTEGER(), nullable=False
    )
    ### end Alembic commands ###


def upgrade_reports():
    pass



def downgrade_reports():
    pass
