"""empty message

Revision ID: 3317ba4417dc
Revises: 58fee14dec42
Create Date: 2017-08-30 13:03:32.354462

"""

# revision identifiers, used by Alembic.
revision = '3317ba4417dc'
down_revision = '58fee14dec42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('can_download', sa.Boolean(), server_default='true', nullable=False))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'can_download')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

