"""empty message

Revision ID: 3457b2078d28
Revises: 24391637c175
Create Date: 2015-08-12 12:47:06.969439

"""

# revision identifiers, used by Alembic.
revision = '3457b2078d28'
down_revision = '24391637c175'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.Unicode(), nullable=False),
    sa.Column('utm_medium', sa.Unicode(), nullable=False),
    sa.Column('utm_campaign', sa.Unicode(), nullable=False),
    sa.Column('utm_term', sa.Unicode(), nullable=True),
    sa.Column('utm_content', sa.Unicode(), nullable=True),
    sa.Column('entrance_path', sa.Unicode(), nullable=False),
    sa.Column('is_repeated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'user_activity', 'content')
    op.drop_column(u'user_activity', 'source')
    op.drop_column(u'user_activity', 'term')
    op.drop_column(u'user_activity', 'medium')
    op.drop_column(u'user_activity', 'campaign')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user_activity', sa.Column('campaign', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user_activity', sa.Column('medium', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user_activity', sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user_activity', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'user_activity', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('referral_tracking')
    ### end Alembic commands ###


def downgrade_reports():
    pass
