"""empty message

Revision ID: 3490c9baf802
Revises: 1766021659c9
Create Date: 2017-09-18 18:20:19.577344

"""

# revision identifiers, used by Alembic.
revision = '3490c9baf802'
down_revision = '1766021659c9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_draft',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Unicode(), nullable=True),
    sa.Column('is_sequential_questions', sa.Boolean(), nullable=False),
    sa.Column('can_skip', sa.Boolean(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False, server_default="0"),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('re_attempts_count', sa.Integer(), nullable=True),
    sa.Column('grading_style', sa.Unicode(), nullable=True),
    sa.Column('grading_points', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=u'quiz_draft_created_by_fkey'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=u'quiz_draft_modified_by_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_draft_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Unicode(), nullable=True),
    sa.Column('is_sequential_questions', sa.Boolean(), nullable=False),
    sa.Column('can_skip', sa.Boolean(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False, server_default="0"),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('re_attempts_count', sa.Integer(), nullable=True),
    sa.Column('grading_style', sa.Unicode(), nullable=True),
    sa.Column('grading_points', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=u'quiz_created_by_fkey'),
    sa.ForeignKeyConstraint(['draft_id'], ['quiz_draft.id'], name=u'quiz_draft_id_fkey'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=u'quiz_modified_by_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_quiz_tenant_id_slug')
    )
    op.create_table('quiz_actitvity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('report_user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_session_id', sa.Unicode(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('total_questions_count', sa.Integer(), nullable=False),
    sa.Column('attempted_questions_count', sa.Integer(), nullable=False),
    sa.Column('skipped_questions_count', sa.Integer(), nullable=False),
    sa.Column('correct_answer_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=False),
    sa.Column('is_timeout', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('locale_requested_code', sa.Unicode(), nullable=True),
    sa.Column('locale_served_code', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['locale_requested_code'], ['languages.id'], name=u'quiz_actitvity_locale_requested_code_fkey'),
    sa.ForeignKeyConstraint(['locale_served_code'], ['languages.id'], name=u'quiz_actitvity_locale_served_code_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=u'quiz_actitvity_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.id'], name=u'quiz_actitvity_report_user_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_actitvity_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_question',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('option_type', sa.Unicode(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=u'quiz_draft_question_created_by_fkey'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=u'quiz_draft_question_modified_by_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_draft.id'], name=u'quiz_draft_question_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_draft_question_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_matching_option',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_draft.id'], name=u'quiz_draft_matching_option_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_draft_question.id'], name=u'quiz_draft_matching_option_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_draft_matching_option_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_matching_option_translation',
    sa.Column('item_left', postgresql.JSON(), nullable=True),
    sa.Column('item_right', postgresql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_matching_option_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_draft_matching_option_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_matching_option_id'], ['quiz_draft_matching_option.id'], name=u'quiz_draft_matching_option_transla_quiz_matching_option_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_multiselect_option',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_correct_option', sa.Boolean(), nullable=False),
    sa.Column('is_single_select', sa.Boolean(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_draft.id'], name=u'quiz_draft_multiselect_option_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_draft_question.id'], name=u'quiz_draft_multiselect_option_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_draft_multiselect_option_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_multiselect_option_translation',
    sa.Column('text', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_multiselect_option_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_draft_multiselect_option_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_draft_multiselect_option_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_multiselect_option_id'], ['quiz_draft_multiselect_option.id'], name=u'quiz_draft_multiselect_option_t_quiz_multiselect_option_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_question_translation',
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_draft_question_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_draft_question_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_draft_question.id'], name=u'quiz_draft_question_translation_quiz_question_id_fkeyquiz_draft_sortable_option_quiz_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_sortable_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('correct_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_draft.id'], name=u'quiz_draft_sortable_option_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_draft_question.id'], name=u'quiz_draft_sortable_option_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_draft_sortable_option_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_sortable_option_translation',
    sa.Column('text', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_sortable_option_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_draft_sortable_option_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_draft_sortable_option_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_sortable_option_id'], ['quiz_draft_sortable_option.id'], name=u'quiz_draft_sortable_option_transla_quiz_sortable_option_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_draft_translation',
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_draft_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_draft_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_draft.id'], name=u'quiz_draft_translation_quiz_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('option_type', sa.Unicode(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=u'quiz_question_created_by_fkey'),
    sa.ForeignKeyConstraint(['draft_id'], ['quiz_draft_question.id'], name=u'quiz_question_draft_id_fkey'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=u'quiz_question_modified_by_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=u'quiz_question_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_question_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_matching_option',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['quiz_draft_matching_option.id'], name=u'quiz_matching_option_draft_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=u'quiz_matching_option_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_question.id'], name=u'quiz_matching_option_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_matching_option_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_matching_option_translation',
    sa.Column('item_left', postgresql.JSON(), nullable=True),
    sa.Column('item_right', postgresql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_matching_option_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_matching_option_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_matching_option_id'], ['quiz_matching_option.id'], name=u'quiz_matching_option_translation_quiz_matching_option_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_multiselect_option',
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('is_correct_option', sa.Boolean(), nullable=False),
    sa.Column('is_single_select', sa.Boolean(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['quiz_draft_multiselect_option.id'], name=u'quiz_multiselect_option_draft_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=u'quiz_multiselect_option_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_question.id'], name=u'quiz_multiselect_option_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_multiselect_option_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_multiselect_option_translation',
    sa.Column('text', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_multiselect_option_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_multiselect_option_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_multiselect_option_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_multiselect_option_id'], ['quiz_multiselect_option.id'], name=u'quiz_multiselect_option_transla_quiz_multiselect_option_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('report_user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('quiz_question_id', sa.Integer(), nullable=True),
    sa.Column('quiz_session_id', sa.Unicode(), nullable=False),
    sa.Column('is_correct_option', sa.Boolean(), nullable=False),
    sa.Column('answers', postgresql.JSON(), nullable=True),
    sa.Column('answer_type', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('locale_requested_code', sa.Unicode(), nullable=True),
    sa.Column('locale_served_code', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['locale_requested_code'], ['languages.id'], name=u'quiz_question_activity_locale_requested_code_fkey'),
    sa.ForeignKeyConstraint(['locale_served_code'], ['languages.id'], name=u'quiz_question_activity_locale_served_code_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=u'quiz_question_activity_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_question.id'], name=u'quiz_question_activity_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.id'], name=u'quiz_question_activity_report_user_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_question_activity_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question_translation',
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_question_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_question_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_question.id'], name=u'quiz_question_translation_quiz_question_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_sortable_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('correct_order', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('quiz_question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['quiz_draft_sortable_option.id'], name=u'quiz_sortable_option_draft_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=u'quiz_sortable_option_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_question_id'], ['quiz_question.id'], name=u'quiz_sortable_option_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'quiz_sortable_option_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_sortable_option_translation',
    sa.Column('text', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_sortable_option_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_sortable_option_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_sortable_option_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_sortable_option_id'], ['quiz_sortable_option.id'], name=u'quiz_sortable_option_translation_quiz_sortable_option_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_translation',
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['icon_library.id'], name=u'quiz_translation_icon_id_fkey'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=u'quiz_translation_language_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name=u'quiz_translation_quiz_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_actitvity')
    op.drop_table('quiz_question_activity')
    op.drop_table('quiz_draft_sortable_option_translation')
    op.drop_table('quiz_draft_matching_option_translation')
    op.drop_table('quiz_draft_multiselect_option_translation')
    op.drop_table('quiz_draft_question_translation')
    op.drop_table('quiz_draft_translation')
    op.drop_table('quiz_sortable_option_translation')
    op.drop_table('quiz_sortable_option')
    op.drop_table('quiz_draft_sortable_option')
    op.drop_table('quiz_matching_option_translation')
    op.drop_table('quiz_matching_option')
    op.drop_table('quiz_draft_matching_option')
    op.drop_table('quiz_multiselect_option_translation')
    op.drop_table('quiz_multiselect_option')
    op.drop_table('quiz_draft_multiselect_option')
    op.drop_table('quiz_question_translation')
    op.drop_table('quiz_question')
    op.drop_table('quiz_draft_question')
    op.drop_table('quiz_translation')
    op.drop_table('quiz')
    op.drop_table('quiz_draft')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
