"""empty message

Revision ID: 36ef52da5892
Revises: 4bfaff72f91b
Create Date: 2015-07-10 10:02:57.389742

"""

# revision identifiers, used by Alembic.
revision = '36ef52da5892'
down_revision = '25d8a6172167'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slide', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('draft_slide', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))

    op.drop_column('resource', 'walkthrough_id')
    op.execute("delete from walkthrough where id = -1")
    op.execute("delete from draft_walkthrough where section_id = -1")
    op.execute("delete from section where id = -1")
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.add_column('resource', sa.Column('walkthrough_id', sa.INTEGER(), autoincrement=False, nullable=True))

    query = bind.execute("select * from section where id = -1")
    section = query.fetchone()
    if not section:
        bind.execute(
            """insert into section(id, "order", tenant_id, is_hidden, is_enabled, is_deleted, created_at, modified_at) values (-1, 1, -1, false, true, true, '2015-07-09', '2015-07-09')""")

    query = bind.execute("select * from tenant where id = -1")
    tenant = query.fetchone()
    if not tenant:
        bind.execute("""insert into tenant values (-1, 'Default', 'default:5000', '2015-01-01', '2015-01-01')""")

    bind.execute(
        """insert into draft_walkthrough(id, resource_hostname, "order", tenant_id, section_id, is_enabled, is_deleted, created_at, modified_at) values (-1, 'localhost', 1, -1, -1, true, true, '2015-07-09', '2015-07-09')""")

    bind.execute(
        """insert into walkthrough(id, resource_hostname, "order", tenant_id, section_id, draft_id, is_enabled, is_deleted, created_at, modified_at) values (-1, 'localhost', 1, -1, -1, -1, true, true, '2015-07-09', '2015-07-09')""")
    op.execute("update resource set walkthrough_id=-1 where walkthrough_id is null")

    op.alter_column(
        'resource', 'walkthrough_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.drop_column('draft_slide', 'is_deleted')
    op.drop_column('slide', 'is_deleted')
    ### end Alembic commands ###


def downgrade_reports():
    pass
