"""empty message

Revision ID: 36f26f20bd4
Revises: 566801742ff6
Create Date: 2015-12-01 20:27:34.118222

"""

# revision identifiers, used by Alembic.
revision = '36f26f20bd4'
down_revision = '5a942d4048f1'
branch_labels = None
depends_on = None

from alembic import op


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS user_tenant_email")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_username_key")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_user_tenant_id_email")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_user_tenant_id_username")
    op.create_unique_constraint('uq_user_tenant_id_email', 'users', ['tenant_id', 'email'])
    op.create_unique_constraint('uq_user_tenant_id_username', 'users', ['tenant_id', 'username'])
    # end Alembic commands #


def downgrade_():
    """Constraint not removed as it may impact on user accounts created here after"""
    pass


def upgrade_reports():
    pass


def downgrade_reports():
    pass
