"""empty message

Revision ID: 377433b2972b
Revises: 2d505cdb960e
Create Date: 2015-02-05 13:21:47.538415

"""

# revision identifiers, used by Alembic.
revision = '377433b2972b'
down_revision = '2d505cdb960e'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_theme', sa.Column('hover_border_color', sa.Unicode(), nullable=False))
    op.drop_column('tenant_theme', 'right_border_color_hover')
    op.drop_column('tenant_theme', 'left_border_color')
    op.drop_column('tenant_theme', 'left_border_color_hover')
    op.drop_column('tenant_theme', 'right_border_color')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    op.add_column('tenant_theme', sa.Column('right_border_color', sa.VARCHAR(), server_default=u' ', autoincrement=False, nullable=False))
    op.add_column('tenant_theme', sa.Column('left_border_color_hover', sa.VARCHAR(), server_default=u' ', autoincrement=False, nullable=False))
    op.add_column('tenant_theme', sa.Column('left_border_color', sa.VARCHAR(), server_default=u' ', autoincrement=False, nullable=False))
    op.add_column('tenant_theme', sa.Column('right_border_color_hover', sa.VARCHAR(), server_default=u' ', autoincrement=False, nullable=False))
    op.drop_column('tenant_theme', 'hover_border_color')
    ### end Alembic commands ###


def downgrade_reports():
    pass
