"""empty message

Revision ID: 37d533190b01
Revises: 1620c33cf97
Create Date: 2016-10-26 12:52:49.006540

"""

# revision identifiers, used by Alembic.
revision = '37d533190b01'
down_revision = '1620c33cf97'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('idp_email', sa.Unicode(), nullable=True))
    op.add_column('tenant', sa.Column('idp_first_name', sa.Unicode(), nullable=True))
    op.add_column('tenant', sa.Column('idp_last_name', sa.Unicode(), nullable=True))
    op.add_column('tenant', sa.Column('idp_username', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'idp_username')
    op.drop_column('tenant', 'idp_last_name')
    op.drop_column('tenant', 'idp_first_name')
    op.drop_column('tenant', 'idp_email')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

