"""empty message

Revision ID: 37f4c009318f
Revises: 7237dfeb649
Create Date: 2015-06-16 08:45:28.487369

"""

# revision identifiers, used by Alembic.
revision = '37f4c009318f'
down_revision = '7237dfeb649'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.execute("insert into tenant values (-1, 'Default', 'default:5000', '2015-01-01', '2015-01-01')")
    op.execute("update hotspot set tenant_id=-1 where tenant_id is null")
    op.execute("update icon_library set tenant_id=-1 where tenant_id is null")
    op.execute("update resource set tenant_id=-1 where tenant_id is null")
    op.execute("update section set tenant_id=-1 where tenant_id is null")
    op.execute("update slide set tenant_id=-1 where tenant_id is null")
    op.execute("update walkthrough set tenant_id=-1 where tenant_id is null")

    op.alter_column('hotspot', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default='1')
    op.alter_column('icon_library', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default='1')
    op.alter_column('leads', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('resource', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default='1')
    op.add_column('section', sa.Column('is_deleted', sa.Boolean(),
                  server_default='false',
                  nullable=False))
    op.alter_column('section', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default='1')
    op.alter_column('slide', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default='1')
    op.add_column('tenant', sa.Column('title', sa.Unicode(), nullable=True))
    op.add_column('walkthrough', sa.Column('is_deleted', sa.Boolean(),
                  server_default='false',
                  nullable=False))
    op.alter_column('walkthrough', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    server_default='1')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column('walkthrough', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    server_default='1')
    op.drop_column('walkthrough', 'is_deleted')
    op.drop_column('tenant', 'title')
    op.alter_column('slide', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    server_default='1')
    op.alter_column('section', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    server_default='1')
    op.drop_column('section', 'is_deleted')
    op.alter_column('resource', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    server_default='1')
    op.alter_column('leads', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('icon_library', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    server_default='1')
    op.alter_column('hotspot', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    server_default='1')

    op.execute("update walkthrough set tenant_id=NULL where tenant_id=-1")
    op.execute("update slide set tenant_id=NULL where tenant_id=-1")
    op.execute("update section set tenant_id=NULL where tenant_id=-1")
    op.execute("update resource set tenant_id=NULL where tenant_id=-1")
    op.execute("update icon_library set tenant_id=NULL where tenant_id=-1")
    op.execute("update hotspot set tenant_id=NULL where tenant_id=-1")
    # end Alembic commands #


def downgrade_reports():
    pass
