"""empty message

Revision ID: 397e0841ad63
Revises: 4d9c12bd9b16
Create Date: 2019-05-20 12:37:20.438637

"""

# revision identifiers, used by Alembic.
revision = '397e0841ad63'
down_revision = '4d9c12bd9b16'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sample_exchange',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Unicode(), nullable=True),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('result_title', sa.Unicode(), nullable=True),
        sa.Column('platform', postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.Unicode()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id'),
        sa.UniqueConstraint('tenant_id')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_exchange')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
