"""empty message

Revision ID: 3b144ad3b352
Revises: 3e6e7dbea83
Create Date: 2016-11-15 14:49:59.054724

"""

# revision identifiers, used by Alembic.
revision = '3b144ad3b352'
down_revision = '3e6e7dbea83'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'section_link_id_fkey', 'section', type_='foreignkey')
    op.drop_column('section', 'link_id')
    op.drop_constraint(u'walkthrough_link_id_fkey', 'walkthrough', type_='foreignkey')
    op.drop_column('walkthrough', 'link_id')
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walkthrough', sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'walkthrough_link_id_fkey', 'walkthrough', 'walkthrough', ['link_id'], ['id'])
    op.add_column('section', sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'section_link_id_fkey', 'section', 'section', ['link_id'], ['id'])
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
