"""empty message

Revision ID: 3b277c3682e1
Revises: 2183b5640bf2
Create Date: 2019-12-02 10:04:32.335739

"""

# revision identifiers, used by Alembic.
revision = '3b277c3682e1'
down_revision = '2183b5640bf2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()



def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homepage_banner_translations', 'background_image_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('homepage_banner_translations', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
