"""empty message

Revision ID: 3b73676abbd1
Revises: 5c7954bc61d
Create Date: 2018-06-18 06:28:13.708937

"""

# revision identifiers, used by Alembic.
revision = '3b73676abbd1'
down_revision = '5c7954bc61d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'section_video',
        sa.Column(
            'language_id',
            sa.Unicode(),
            nullable=True
        )
    )
    op.create_foreign_key(
        'section_video_language_id_fkey',
        'section_video',
        'languages',
        ['language_id'],
        ['id']
    )

    bind = op.get_bind()
    query = bind.execute("""select t.default_locale_id, sv.section_id
                         from section_video sv
                         join section s on sv.section_id = s.id
                         join tenant t on s.tenant_id = t.id""")
    section_videos = query.fetchall()

    for video in section_videos:
        bind.execute(
            """
                update section_video
                set language_id=%(l_id)s
                where section_id=%(s_id)s
            """,
            l_id=video.default_locale_id,
            s_id=video.section_id)

    op.alter_column(
        'section_video', 'language_id',
        existing_type=sa.Unicode(),
        nullable=False
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_video', 'language_id')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
