"""empty message

Revision ID: 3d092264319e
Revises: 46f2cd21e0ac
Create Date: 2016-03-29 10:05:12.513960

"""

# revision identifiers, used by Alembic.
revision = '3d092264319e'
down_revision = '229cfa5d5d5f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('section', sa.Column('analytics', sa.Unicode(), nullable=True))
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('section', 'analytics')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
