"""empty message

Revision ID: 3f11838e1175
Revises: 58eb01ed6ffa
Create Date: 2015-03-13 16:38:18.124235

"""

# revision identifiers, used by Alembic.
revision = '3f11838e1175'
down_revision = '58eb01ed6ffa'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'walkthrough_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()

    leads_query = bind.execute("select * from leads where walkthrough_id is null")
    lead = leads_query.fetchone()

    if lead:
        walkthrough_query = bind.execute("select * from walkthrough where id=-1")
        walkthrough = walkthrough_query.fetchone()
        if walkthrough:
            op.execute("update leads set walkthrough_id=" + str(walkthrough.id) + " where walkthrough_id is null")
        else:
            bind.execute("""insert into walkthrough(id, resource_hostname, "order", tenant_id, section_id, draft_id, is_enabled, is_deleted, created_at, modified_at) values (-1, 'localhost', 1, -1, -1, -1, true, true, '2015-07-09', '2015-07-09')""")    
            op.execute("update leads set walkthrough_id=-1 where walkthrough_id is null")

    op.alter_column('leads', 'walkthrough_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    ### end Alembic commands ###


def downgrade_reports():
    pass
