"""empty message

Revision ID: 3f86eb555b5e
Revises: 397e0841ad63
Create Date: 2019-06-16 16:52:44.510347

"""

# revision identifiers, used by Alembic.
revision = '3f86eb555b5e'
down_revision = '397e0841ad63'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_parser',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Unicode(), nullable=False),
        sa.Column('input_file', sa.Unicode(), nullable=False),
        sa.Column('output_file', sa.Unicode(), nullable=True),
        sa.Column('token', sa.Unicode(), nullable=True),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('status', sa.Unicode(), nullable=False),
        sa.Column('is_canceled', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('section_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=u'document_parser_created_by_fkey'),
        sa.ForeignKeyConstraint(['section_id'], ['section.id'], name=u'document_parser_section_id_fkey'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'document_parser_tenant_id_fkey'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token', name='uq_document_parser_token')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_parser')
    ### end Alembic commands ###
    

def upgrade_reports():
    pass


def downgrade_reports():
    pass

