"""empty message

Revision ID: 4009d18a5711
Revises: 16af01d0ee71
Create Date: 2015-09-03 12:20:18.142583

"""

# revision identifiers, used by Alembic.
revision = '4009d18a5711'
down_revision = '16af01d0ee71'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral_tracking', 'utm_campaign',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('referral_tracking', 'utm_medium', new_column_name='medium')
    op.alter_column('referral_tracking', 'utm_source', new_column_name='source')
    op.alter_column('referral_tracking', 'utm_term', new_column_name='term')
    op.alter_column('referral_tracking', 'utm_content', new_column_name='content')
    op.alter_column('referral_tracking', 'utm_campaign', new_column_name='campaign')
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('referral_tracking', 'source', new_column_name='utm_source')
    op.alter_column('referral_tracking', 'medium', new_column_name='utm_medium')
    op.alter_column('referral_tracking', 'term', new_column_name='utm_term')
    op.alter_column('referral_tracking', 'content', new_column_name='utm_content')
    op.alter_column('referral_tracking', 'campaign', new_column_name='utm_campaign')
    op.alter_column('referral_tracking', 'utm_campaign',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
