"""empty message

Revision ID: 40d7c9a8ce8b
Revises: ba1fab22f66
Create Date: 2014-12-26 18:38:15.533081

"""

# revision identifiers, used by Alembic.
revision = '40d7c9a8ce8b'
down_revision = 'ba1fab22f66'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('domain', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'completion_activity', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'hotspot', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'icon_library', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'resource', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'section', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'slide', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'visit_activity', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'walkthrough', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column(u'walkthrough_activity', sa.Column('tenant_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'walkthrough_activity', 'tenant_id')
    op.drop_column(u'walkthrough', 'tenant_id')
    op.drop_column(u'visit_activity', 'tenant_id')
    op.drop_column(u'slide', 'tenant_id')
    op.drop_column(u'section', 'tenant_id')
    op.drop_column(u'resource', 'tenant_id')
    op.drop_column(u'icon_library', 'tenant_id')
    op.drop_column(u'hotspot', 'tenant_id')
    op.drop_column(u'completion_activity', 'tenant_id')
    op.drop_table('tenant')
    ### end Alembic commands ###


def downgrade_reports():
    pass
