"""empty message

Revision ID: 4137c03c4e18
Revises: 1f44f850630b
Create Date: 2018-08-02 10:23:25.346796

"""

# revision identifiers, used by Alembic.
revision = '4137c03c4e18'
down_revision = '1f44f850630b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_translations', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.create_foreign_key('section_translations_resource_id_fkey', 'section_translations', 'resource', ['resource_id'], ['id'])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_translations_resource_id_fkey', 'section_translations', type_='foreignkey')
    op.drop_column('section_translations', 'resource_id')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

