"""empty message

Revision ID: 4215e4021438
Revises: 9e3a7f221b4
Create Date: 2019-10-17 10:36:03.075954

"""

# revision identifiers, used by Alembic.
revision = '4215e4021438'
down_revision = '9e3a7f221b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS apscheduler_jobs")
    op.drop_table('scheduler')
    op.create_table(
        'expiry_job',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entity_type', sa.Unicode(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('expire_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('is_executed', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('modified_by', sa.Integer(), nullable=False),
        sa.Column('author_locale', sa.Unicode(), nullable=False),
        sa.ForeignKeyConstraint(['author_locale'], ['languages.id'], name=u'expiry_job_languages_id_fkey'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=u'expiry_job_created_users_id_fkey'),
        sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=u'expiry_job_modified_users_id_fkey'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=u'expiry_job_tenant_id_fkey'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_type', 'entity_id', name='uq_entity_type_id')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expiry_job')
    op.create_table(
        'scheduler',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], [u'tenant.id'], name=u'scheduler_tenant_id_fkey'),
        sa.PrimaryKeyConstraint('id', name=u'scheduler_pkey'),
        sa.UniqueConstraint('entity_type', 'entity_id', name=u'uq_entity_type_id'),
        sa.UniqueConstraint('job_id', name=u'uq_scheduler_job_id')
    )
    op.create_table(
        'apscheduler_jobs',
        sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
        sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
