"""empty message

Revision ID: 42a04e03271
Revises: 5429fb6716cd
Create Date: 2017-02-24 05:19:49.753346

"""

# revision identifiers, used by Alembic.
revision = '42a04e03271'
down_revision = '5429fb6716cd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.create_foreign_key('information_icon_id_fkey', 'information', 'icon_library', ['icon_id'], ['id'])
    op.add_column('options', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.create_foreign_key('options_icon_id_fkey', 'options', 'icon_library', ['icon_id'], ['id'])
    op.add_column('questions', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.create_foreign_key('questions_icon_id_fkey', 'questions', 'icon_library', ['icon_id'], ['id'])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_icon_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'icon_id')
    op.drop_constraint('options_icon_id_fkey', 'options', type_='foreignkey')
    op.drop_column('options', 'icon_id')
    op.drop_constraint('information_icon_id_fkey', 'information', type_='foreignkey')
    op.drop_column('information', 'icon_id')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

