"""empty message

Revision ID: 430947222727
Revises: 1d832a6e8e61
Create Date: 2019-02-18 06:42:26.944283

"""

# revision identifiers, used by Alembic.
revision = '430947222727'
down_revision = '1d832a6e8e61'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sample_exchange_activity',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sample_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.Unicode(), nullable=True),
        sa.Column('author', sa.Unicode(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('report_user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_exchange_activity')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
