"""empty message

Revision ID: 43210d67a907
Revises: 44924266fa47
Create Date: 2015-11-04 22:55:35.027537

"""

# revision identifiers, used by Alembic.
revision = '43210d67a907'
down_revision = '44924266fa47'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('privacy_link', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'privacy_link')
    ### end Alembic commands ###


def upgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("update topic_activity set product='' where product is NULL");
    op.alter_column('topic_activity', 'product',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic_activity', 'product',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###

