"""empty message

Revision ID: 44924266fa47
Revises: 526b329bdc6e
Create Date: 2015-10-26 23:32:15.242282

"""

# revision identifiers, used by Alembic.
revision = '44924266fa47'
down_revision = '526b329bdc6e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('website_url', sa.Unicode(), nullable=False),
    sa.Column('logo_url', sa.Unicode(), nullable=True),
    sa.Column('unique_link_id', sa.Unicode(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audience_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(), nullable=False),
    sa.Column('last_name', sa.Unicode(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('picture_url', sa.Unicode(), nullable=True),
    sa.Column('is_admin_added', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['audience_companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'company_id', name='_company_employee_email')
    )
    op.create_table('audience_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['audience_companies.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audience_sections')
    op.drop_table('audience_employees')
    op.drop_table('audience_companies')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

