"""empty message

Revision ID: 466a96f1881b
Revises: 9c9b66e42e4
Create Date: 2017-04-10 05:17:45.482099

"""

# revision identifiers, used by Alembic.
revision = '466a96f1881b'
down_revision = '9c9b66e42e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_store',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=u'access_token_store_pkey')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token_store')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
