"""empty message

Revision ID: 468fd6de0682
Revises: 334a6183b026
Create Date: 2016-05-30 11:31:50.842934

"""

# revision identifiers, used by Alembic.
revision = '468fd6de0682'
down_revision = '334a6183b026'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_theme', 'text_color', new_column_name='title_color')
    op.add_column('tenant_theme', sa.Column('paragraph_color', sa.Unicode(), nullable=False, server_default=u'#ffffff'))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_theme', 'paragraph_color')
    op.alter_column('tenant_theme', 'title_color', new_column_name='text_color')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

