"""empty message

Revision ID: 46f2cd21e0ac
Revises: 2c9a7981d8c
Create Date: 2016-03-10 18:08:07.433705

"""

# revision identifiers, used by Alembic.
revision = '46f2cd21e0ac'
down_revision = '2c9a7981d8c'
branch_labels = None
depends_on = None

from alembic import op


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_reports():
    pass


def downgrade_reports():
    pass


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE social_auth_usersocialauth DROP CONSTRAINT IF EXISTS social_auth_usersocialauth_provider_uid_key")
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'social_auth_usersocialauth_provider_uid_key', 'social_auth_usersocialauth', ['provider', 'uid'])
    ### end Alembic commands ###
