"""empty message

Revision ID: 47ca7d119706
Revises: 3457b2078d28
Create Date: 2015-08-14 12:16:15.200415

"""

# revision identifiers, used by Alembic.
revision = '47ca7d119706'
down_revision = '3457b2078d28'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('ip_address', sa.Unicode(), nullable=True))
    op.add_column('user_activity', sa.Column('city', sa.Unicode(), nullable=True))
    op.add_column('user_activity', sa.Column('state', sa.Unicode(), nullable=True))
    op.add_column('user_activity', sa.Column('country', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activity', 'country')
    op.drop_column('user_activity', 'state')
    op.drop_column('user_activity', 'city')
    op.drop_column('user_activity', 'ip_address')
    ### end Alembic commands ###


def downgrade_reports():
    pass
