"""empty message

Revision ID: 47f643067f
Revises: 566801742ff6
Create Date: 2015-12-17 01:10:50.725759

"""

# revision identifiers, used by Alembic.
revision = '47f643067f'
down_revision = '566801742ff6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_reports():
    pass


def downgrade_reports():
    pass


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('idp_entity_id', sa.Unicode(), nullable=True))
    op.add_column('tenant', sa.Column('idp_url', sa.Unicode(), nullable=True))
    op.add_column('tenant', sa.Column('idp_x509cert', sa.Text(), nullable=True))
    op.add_column('tenant', sa.Column('sp_private_key', sa.Text(), nullable=True))
    op.add_column('tenant', sa.Column('sp_public_certificate', sa.Text(), nullable=True))

    op.alter_column('users', 'role_id', server_default='3')
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'sp_public_certificate')
    op.drop_column('tenant', 'sp_private_key')
    op.drop_column('tenant', 'idp_x509cert')
    op.drop_column('tenant', 'idp_url')
    op.drop_column('tenant', 'idp_entity_id')

    op.alter_column('users', 'role_id', server_default='1')
    ### end Alembic commands ###
