"""empty message

Revision ID: 49933a352ef
Revises: 4a96301ba37a
Create Date: 2017-06-13 15:24:20.794339

"""

# revision identifiers, used by Alembic.
revision = '49933a352ef'
down_revision = '4a96301ba37a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    op.execute(""" UPDATE resource SET meta_data = '{}'::json WHERE meta_data::text = 'null'; """)
    op.alter_column('resource', 'meta_data', server_default='{}', nullable=True)
    # pass


def downgrade_():
    op.alter_column('resource', 'meta_data', server_default=None, nullable=True)
    # pass


def upgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

