"""empty message

Revision ID: 4a96301ba37a
Revises: 1ab300a55552
Create Date: 2017-06-01 11:32:03.546801

"""

# revision identifiers, used by Alembic.
revision = '4a96301ba37a'
down_revision = '1ab300a55552'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'frames', new_column_name='meta_data')
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'meta_data', new_column_name='frames')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
