"""empty message

Revision ID: 4b8b73c5edfb
Revises: 3a965f8022
Create Date: 2016-01-04 22:28:04.755500

"""

# revision identifiers, used by Alembic.
revision = '4b8b73c5edfb'
down_revision = '3a965f8022'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('draft_slide_translations', sa.Column('title', sa.Unicode(), nullable=True))
    op.add_column('slide_translations', sa.Column('title', sa.Unicode(), nullable=True))
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('slide_translations', 'title')
    op.drop_column('draft_slide_translations', 'title')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
