"""empty message

Revision ID: 4bcbc47368cc
Revises: 520072eed16
Create Date: 2015-11-09 23:14:37.007927

"""

# revision identifiers, used by Alembic.
revision = '4bcbc47368cc'
down_revision = '520072eed16'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    query = conn.execute("select * from tenant where id = -1")
    tenant = query.fetchone()
    if not tenant:
        op.execute("insert into tenant(id, name, domain, timezone, created_at, modified_at) values (-1, 'Default', 'default:5000', 'US/Pacific', '2015-01-01', '2015-01-01')")
    op.execute("update user_activity set tenant_id=-1 where tenant_id is NULL")
    op.alter_column('user_activity', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('user_tenant_email', 'users', ['email', 'tenant_id'])
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS user_tenant_email")
    op.alter_column('user_activity', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
