"""empty message

Revision ID: 4bfdbb619c22
Revises: 3f11838e1175
Create Date: 2015-04-13 08:49:54.305421

"""

# revision identifiers, used by Alembic.
revision = '4bfdbb619c22'
down_revision = '3f11838e1175'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Unicode(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'section', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=u'false'))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'section', 'is_hidden')
    op.drop_table('product_relationship')
    ### end Alembic commands ###


def downgrade_reports():
    pass
