"""empty message

Revision ID: 4c07b9830a2
Revises: 55f208c6fac9
Create Date: 2015-01-22 10:10:58.198659

"""

# revision identifiers, used by Alembic.
revision = '4c07b9830a2'
down_revision = '55f208c6fac9'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walkthrough', sa.Column('slide_transition_effect', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walkthrough', 'slide_transition_effect')
    ### end Alembic commands ###


def downgrade_reports():
    pass
