"""empty message

Revision ID: 4c921b112426
Revises: 160f7edb843c
Create Date: 2014-11-15 16:45:16.240400

"""

# revision identifiers, used by Alembic.
revision = '4c921b112426'
down_revision = '160f7edb843c'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('unique_user_id', sa.Unicode(), nullable=False),
    sa.Column('browser', sa.Unicode(), nullable=False),
    sa.Column('version', sa.Unicode(), nullable=False),
    sa.Column('platform', sa.Unicode(), nullable=False),
    sa.Column('language', sa.Unicode(), nullable=True),
    sa.Column('source', sa.Unicode(), nullable=True),
    sa.Column('medium', sa.Unicode(), nullable=True),
    sa.Column('term', sa.Unicode(), nullable=True),
    sa.Column('campaign', sa.Unicode(), nullable=True),
    sa.Column('content', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('unique_user_id')
    )
    op.create_table('completion_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_user_id', sa.Unicode(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_total', sa.Integer(), nullable=False),
    sa.Column('entity_complete', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.unique_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walkthrough_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_user_id', sa.Unicode(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('walkthrough_id', sa.Integer(), nullable=False),
    sa.Column('slide_index', sa.Integer(), nullable=False),
    sa.Column('revisit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.unique_user_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthrough.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walkthrough_activity')
    op.drop_table('completion_activity')
    op.drop_table('user_activity')
    ### end Alembic commands ###


def downgrade_reports():
    pass
