"""empty message

Revision ID: 4d53f869526
Revises: 55ee916ba5fd
Create Date: 2016-08-18 06:29:59.869838

"""

# revision identifiers, used by Alembic.
revision = '4d53f869526'
down_revision = '55ee916ba5fd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('chapter_autoflow', sa.Boolean(), nullable=False, server_default="false"))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'chapter_autoflow')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass