"""empty message

Revision ID: 4d9c12bd9b16
Revises: 1743555b4321
Create Date: 2019-05-15 11:44:07.568932

"""

# revision identifiers, used by Alembic.
revision = '4d9c12bd9b16'
down_revision = '1743555b4321'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'mail_digest',
        sa.Column('show_new_content', sa.Boolean(),
                  server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail_digest', 'show_new_content')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
