"""empty message

Revision ID: 5015b2e3ed64
Revises: 1ed78ec8a766
Create Date: 2014-12-22 11:19:56.519145

"""

# revision identifiers, used by Alembic.
revision = '5015b2e3ed64'
down_revision = '1ed78ec8a766'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column



def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walkthrough_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('walkthrough_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthrough.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('text', sa.Unicode(), nullable=False),
    sa.Column('slide_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['slide_id'], ['slide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotspot_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('callout', postgresql.JSON(), nullable=True),
    sa.Column('hotspot_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspot.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'completion_activity', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column(u'hotspot', 'callout')
    op.drop_column(u'section', 'description')
    op.drop_column(u'section', 'name')
    op.drop_column(u'section', 'title')
    op.drop_column(u'slide', 'text')
    op.drop_column(u'slide', 'name')
    op.drop_column(u'walkthrough', 'name')
    op.drop_column(u'walkthrough', 'title')
    op.alter_column(u'walkthrough_activity', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'walkthrough_activity', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.add_column(u'walkthrough', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'walkthrough', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))

    walkthrough = table('walkthrough', column('title'), column('name'))
    op.execute(walkthrough.update().values(title="", name=""))

    op.alter_column('walkthrough', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('walkthrough', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.add_column(u'slide', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'slide', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))

    slide = table('slide', column('name'), column('text'))
    op.execute(slide.update().values(name="", text=""))

    op.alter_column('slide', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('slide', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.add_column(u'section', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'section', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(u'section', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))

    section = table('section', column('title'), column('name'))
    op.execute(section.update().values(title="", name=""))

    op.alter_column('section', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('section', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.add_column(u'hotspot', sa.Column('callout', postgresql.JSON(), autoincrement=False, nullable=True))
    op.alter_column(u'completion_activity', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('hotspot_translations')
    op.drop_table('slide_translations')
    op.drop_table('walkthrough_translations')
    op.drop_table('section_translations')
    op.drop_table('languages')
    ### end Alembic commands ###


def downgrade_reports():
    pass
