"""empty message

Revision ID: 50c97f5e0f10
Revises: 59d874b6d0dc
Create Date: 2017-05-31 13:15:40.209567

"""

# revision identifiers, used by Alembic.
revision = '50c97f5e0f10'
down_revision = '59d874b6d0dc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_item', sa.Column('order', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_item', 'order')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
