"""empty message

Revision ID: 50fb331bb6a1
Revises: 3d092264319e
Create Date: 2016-04-05 06:31:35.339946

"""

# revision identifiers, used by Alembic.
revision = '50fb331bb6a1'
down_revision = '3d092264319e'
branch_labels = None
depends_on = None

from alembic import op


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.execute("""INSERT INTO role VALUES
               (4, 'viewer', '2016-04-05')""")
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.execute("""UPDATE users SET role_id=3 WHERE role_id=4""")
    op.execute("""DELETE FROM role WHERE id = 4""")
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
