"""empty message

Revision ID: 51ad2a881595
Revises: 2c9a7981d8c
Create Date: 2016-03-10 11:43:55.509035

"""

# revision identifiers, used by Alembic.
revision = '51ad2a881595'
down_revision = '46f2cd21e0ac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_reports():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('topic_activity', sa.Column('average_frames_completed', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('topic_activity', sa.Column('percent_completions_25', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('topic_activity', sa.Column('percent_completions_50', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('topic_activity', sa.Column('percent_completions_75', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('topic_activity', sa.Column('percent_completions_100', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('topic_activity', sa.Column('total_slides_count', sa.Integer(), nullable=False, server_default='0'))
    # end Alembic commands #


def downgrade_reports():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('topic_activity', 'total_slides_count')
    op.drop_column('topic_activity', 'percent_completions_100')
    op.drop_column('topic_activity', 'percent_completions_75')
    op.drop_column('topic_activity', 'percent_completions_50')
    op.drop_column('topic_activity', 'percent_completions_25')
    op.drop_column('topic_activity', 'average_frames_completed')
    # end Alembic commands #
