"""empty message

Revision ID: 5268b2608b35
Revises: 5015b2e3ed64
Create Date: 2014-12-26 07:50:56.310020

"""

# revision identifiers, used by Alembic.
revision = '5268b2608b35'
down_revision = '5015b2e3ed64'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('languages', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.alter_column('section', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('walkthrough', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###

    walkthrough = table('walkthrough', column('slug'))
    op.execute(walkthrough.update().where(walkthrough.c.slug==None).values(slug=""))

    op.alter_column('walkthrough', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)

    section = table('section', column('slug'))
    op.execute(section.update().where(section.c.slug==None).values(slug=""))

    op.alter_column('section', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('languages', 'modified_at')
    op.drop_column('languages', 'created_at')
    ### end Alembic commands ###


def downgrade_reports():
    pass
