"""empty message

Revision ID: 526b329bdc6e
Revises: 2ebb41db7701
Create Date: 2015-10-08 17:30:06.510018

"""

# revision identifiers, used by Alembic.
revision = '526b329bdc6e'
down_revision = '2ebb41db7701'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    op.execute("update tenant set timezone = 'US/Pacific' where timezone is NULL")
    op.alter_column('tenant', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade_():
    op.alter_column('tenant', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)


def upgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("update report_tenant set timezone = 'US/Pacific' where timezone is NULL")
    op.alter_column('report_tenant', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade_reports():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_tenant', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###

