"""empty message

Revision ID: 55c7e1d9da2d
Revises: 438f24acc38d
Create Date: 2015-02-27 13:47:56.661441

"""

# revision identifiers, used by Alembic.
revision = '55c7e1d9da2d'
down_revision = '438f24acc38d'

from alembic import op


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'section_parent_id_order_key', 'section')
    op.drop_constraint(u'slide_walkthrough_id_order_key', 'slide')
    op.drop_constraint(u'walkthrough_section_id_order_key', 'walkthrough')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'walkthrough_section_id_order_key', 'walkthrough', ['section_id', 'order'])
    op.create_unique_constraint(u'slide_walkthrough_id_order_key', 'slide', ['walkthrough_id', 'order'])
    op.create_unique_constraint(u'section_parent_id_order_key', 'section', ['parent_id', 'order'])
    ### end Alembic commands ###


def downgrade_reports():
    pass
