"""empty message

Revision ID: 55ee916ba5fd
Revises: 1de0993ab050
Create Date: 2016-08-02 13:06:18.876864

"""

# revision identifiers, used by Alembic.
revision = '55ee916ba5fd'
down_revision = '297513a46ddd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('tenant', sa.Column('box_integration_enabled', sa.Boolean(), server_default="false", nullable=False))
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('tenant', 'box_integration_enabled')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
