"""empty message

Revision ID: 55f208c6fac9
Revises: 1e3fdb46f58f
Create Date: 2015-01-13 09:27:32.808742

"""

# revision identifiers, used by Alembic.
revision = '55f208c6fac9'
down_revision = '1e3fdb46f58f'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('link_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'link_id')
    ### end Alembic commands ###


def downgrade_reports():
    pass
