"""empty message

Revision ID: 566801742ff6
Revises: 3a2c2977201
Create Date: 2015-12-01 01:00:51.275241

"""

# revision identifiers, used by Alembic.
revision = '566801742ff6'
down_revision = '36f26f20bd4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('tag', sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_tags_tenant_id_tenant', 'tag', 'tenant', ['tenant_id'], ['id'])
    # end Alembic commands ###


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_constraint('fk_tags_tenant_id_tenant', 'tag', type_='foreignkey')
    op.drop_column('tag', 'tenant_id')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
