"""empty message

Revision ID: 58eb01ed6ffa
Revises: 1d9b8b56469a
Create Date: 2015-03-12 10:26:36.659445

"""

# revision identifiers, used by Alembic.
revision = '58eb01ed6ffa'
down_revision = '1d9b8b56469a'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('favicon', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'favicon')
    ### end Alembic commands ###


def downgrade_reports():
    pass
