"""empty message

Revision ID: 5a942d4048f1
Revises: 3a2c2977201
Create Date: 2015-12-02 12:54:49.768481

"""

# revision identifiers, used by Alembic.
revision = '5a942d4048f1'
down_revision = '3a2c2977201'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_video_analytics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('report_user_id', sa.Integer(), nullable=False),
                    sa.Column('walkthrough_id', sa.Integer(), nullable=True),
                    sa.Column('resource_id', sa.Integer(), nullable=True),
                    sa.Column('events', sa.Unicode(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.id'], ),
                    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
                    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthrough.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_video_analytics')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
