"""empty message

Revision ID: 6c6be8cb839
Revises: 44924266fa47
Create Date: 2015-11-03 06:41:42.250908

"""

# revision identifiers, used by Alembic.
revision = '6c6be8cb839'
down_revision = '43210d67a907'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audience_companies', sa.Column('expire_at', sa.DateTime(), nullable=True))
    op.add_column('audience_companies', sa.Column('is_share_whole_site', sa.Boolean(), nullable=False, server_default="false"))
    op.alter_column('audience_sections', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audience_sections', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audience_companies', 'is_share_whole_site')
    op.drop_column('audience_companies', 'expire_at')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
