"""empty message

Revision ID: 7237dfeb649
Revises: 2a43507ae154
Create Date: 2015-05-20 07:59:43.718537

"""

# revision identifiers, used by Alembic.
revision = '7237dfeb649'
down_revision = '4bfdbb619c22'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirect_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_url', sa.Unicode(), nullable=False),
    sa.Column('new_url', sa.Unicode(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_url')
    )
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redirect_url')
    ### end Alembic commands ###


def downgrade_reports():
    pass
