"""empty message

Revision ID: 8be28a074e7
Revises: 4500cd556e83
Create Date: 2016-10-04 14:51:59.391037

"""

# revision identifiers, used by Alembic.
revision = '8be28a074e7'
down_revision = '4500cd556e83'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_digest', sa.Column('is_disabled', sa.Boolean(), server_default='false', nullable=False))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail_digest', 'is_disabled')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
