"""empty message

Revision ID: 8dc145b7ae5
Revises: a44e6636c99
Create Date: 2016-12-07 05:06:13.537509

"""

# revision identifiers, used by Alembic.
revision = '8dc145b7ae5'
down_revision = 'a44e6636c99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('applications', sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'))
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('applications', 'is_enabled')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
