"""empty message

Revision ID: 8fa01cc35fa
Revises: 36ef52da5892
Create Date: 2015-07-27 13:42:44.318942

"""

# revision identifiers, used by Alembic.
revision = '8fa01cc35fa'
down_revision = '36ef52da5892'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_leads', sa.Column('email_sent', sa.Boolean(), server_default='true', nullable=False))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_leads', 'email_sent')
    ### end Alembic commands ###


def downgrade_reports():
    pass
