"""empty message

Revision ID: 986c1081557
Revises: 422c771a630b
Create Date: 2018-02-15 09:22:39.576629

"""

# revision identifiers, used by Alembic.
revision = '986c1081557'
down_revision = '422c771a630b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column('section', sa.Column('faq_group_id', sa.Integer(),
                                       nullable=True))
    op.create_foreign_key('section_faq_group_id_fkey', 'section', 'faq_group',
                          ['faq_group_id'], ['id'])
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_constraint('section_faq_group_id_fkey', 'section',
                       type_='foreignkey')
    op.drop_column('section', 'faq_group_id')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
