"""empty message

Revision ID: 9c9b66e42e4
Revises: 4da5044720e1
Create Date: 2017-03-22 05:20:10.325588

"""

# revision identifiers, used by Alembic.
revision = '9c9b66e42e4'
down_revision = '4da5044720e1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column('walkthrough_activity', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('walkthrough_activity', 'report_user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('walkthrough_activity', 'revisit',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('walkthrough_activity', 'section_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('walkthrough_activity', 'slide_index',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('walkthrough_activity', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('walkthrough_activity', 'walkthrough_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column('walkthrough_activity', 'walkthrough_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('walkthrough_activity', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('walkthrough_activity', 'slide_index',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('walkthrough_activity', 'section_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('walkthrough_activity', 'revisit',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('walkthrough_activity', 'report_user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('walkthrough_activity', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)


def upgrade_reports():
    pass


def downgrade_reports():
    pass
    # end Alembic commands #
