"""empty message

Revision ID: 9e3a7f221b4
Revises: 30a5922f7909
Create Date: 2019-10-16 12:09:55.923847

"""

# revision identifiers, used by Alembic.
revision = '9e3a7f221b4'
down_revision = '30a5922f7909'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_reports():
    pass


def downgrade_reports():
    pass


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_journeys', sa.Column('tags', postgresql.JSON(none_as_null=True), nullable=True))
    op.add_column('journeys', sa.Column('tags', postgresql.JSON(none_as_null=True), nullable=True))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journeys', 'tags')
    op.drop_column('draft_journeys', 'tags')
    ### end Alembic commands ###
