"""empty message

Revision ID: a16a420531f
Revises: 3a965f8022
Create Date: 2016-01-22 10:06:17.940734

"""

# revision identifiers, used by Alembic.
revision = 'a16a420531f'
down_revision = '3a965f8022'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_reports():
    pass


def downgrade_reports():
    pass


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('users', 'first_name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # end Alembic commands #


def downgrade_():
    pass
