"""empty message

Revision ID: a9b0dc54fe1
Revises: 3578e6fe8c6f
Create Date: 2015-08-28 21:55:00.014244

"""

# revision identifiers, used by Alembic.
revision = 'a9b0dc54fe1'
down_revision = '3578e6fe8c6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('timezone', sa.Unicode(), nullable=True))
    op.execute("update tenant set timezone='US/Pacific' where timezone is null")
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'timezone')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
