"""empty message

Revision ID: aac1633b09a
Revises: 173930a0a2b2
Create Date: 2016-04-22 11:51:18.529295

"""

# revision identifiers, used by Alembic.
revision = 'aac1633b09a'
down_revision = '173930a0a2b2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('footer_text', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'footer_text')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

