"""empty message

Revision ID: ae7c63cd8b5
Revises: 3b144ad3b352
Create Date: 2016-11-08 08:45:56.011120

"""

# revision identifiers, used by Alembic.
revision = 'ae7c63cd8b5'
down_revision = '3b144ad3b352'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_activity_user_id', 'user_activity', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_activity_user_id', 'user_activity', type_='foreignkey')
    op.drop_column('user_activity', 'user_id')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass

