"""empty message

Revision ID: ae85cef399
Revises: 266738c026ff
Create Date: 2015-02-03 05:03:03.202572

"""

# revision identifiers, used by Alembic.
revision = 'ae85cef399'
down_revision = '266738c026ff'

from alembic import op


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('section_parent_id_order_key', 'section', ['parent_id', 'order'])
    op.create_unique_constraint('slide_walkthrough_id_order_key', 'slide', ['walkthrough_id', 'order'])
    op.create_unique_constraint('walkthrough_section_id_order_key', 'walkthrough', ['section_id', 'order'])
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('walkthrough_section_id_order_key', 'walkthrough')
    op.drop_constraint('slide_walkthrough_id_order_key', 'slide')
    op.drop_constraint('section_parent_id_order_key', 'section')
    ### end Alembic commands ###


def downgrade_reports():
    pass
