"""empty message

Revision ID: b5a032631f5
Revises: 2137d2ff75b4
Create Date: 2015-01-07 10:51:53.391936

"""

# revision identifiers, used by Alembic.
revision = 'b5a032631f5'
down_revision = '2137d2ff75b4'

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Unicode(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'section', 'video_url')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'section', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('section_video')
    ### end Alembic commands ###


def downgrade_reports():
    pass
