"""empty message

Revision ID: c3e27c3e3e6
Revises: 1316d35d9acc
Create Date: 2017-10-26 11:29:54.787983

"""

# revision identifiers, used by Alembic.
revision = 'c3e27c3e3e6'
down_revision = '1316d35d9acc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.add_column(
        'quiz_draft_translation',
        sa.Column('certification',
                  sa.Unicode(),
                  nullable=False,
                  server_default=u''))
    op.add_column(
        'quiz_translation',
        sa.Column('certification',
                  sa.Unicode(),
                  nullable=False,
                  server_default=u''))
    conn = op.get_bind()
    conn.execute("update quiz_draft set grading_style = lower(grading_style)")
    conn.execute(
        "update quiz_draft set grading_style = replace(grading_style, ' ', '_')"
    )
    conn.execute("update quiz set grading_style = lower(grading_style)")
    conn.execute(
        "update quiz set grading_style = replace(grading_style, ' ', '_')"
    )
    # end Alembic commands #


def downgrade_():
    # commands auto generated by Alembic - please adjust! #
    op.drop_column('quiz_translation', 'certification')
    op.drop_column('quiz_draft_translation', 'certification')
    # end Alembic commands #


def upgrade_reports():
    pass


def downgrade_reports():
    pass
