"""empty message

Revision ID: e04df8bed24
Revises: 25a95bf846db
Create Date: 2019-09-03 06:42:32.646541

"""

# revision identifiers, used by Alembic.
revision = 'e04df8bed24'
down_revision = '25a95bf846db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'homepage_banner',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('modified_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'homepage_banner_cta',
        sa.Column('cta_id', sa.Integer(), nullable=False),
        sa.Column('banner_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['banner_id'], ['homepage_banner.id'], ),
        sa.ForeignKeyConstraint(['cta_id'], ['lead_cta_form.id'], ),
        sa.PrimaryKeyConstraint('cta_id', 'banner_id')
    )
    op.create_table(
        'homepage_banner_translations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Unicode(), nullable=False),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('banner_id', sa.Integer(), nullable=False),
        sa.Column('language_id', sa.Unicode(), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('background_image_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('modified_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['background_image_id'], ['resource.id'], ),
        sa.ForeignKeyConstraint(['banner_id'], ['homepage_banner.id'], ),
        sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
        sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.alter_column(u'cta_activity', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)

    op.add_column(
        u'tenant_flags',
        sa.Column(
            'enable_homepage_banner',
            sa.Boolean(), nullable=False, server_default='false')
    )
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tenant_flags', 'enable_homepage_banner')
    """
    After logging the cta_activity from home page(end site)
    product_id contain's null values,
    so we can not downgrade the product_id column to nullable False Modifier.
    """
    # op.alter_column(u'cta_activity', 'product_id',
    #                 existing_type=sa.INTEGER(),
    #                 nullable=False)
    op.drop_table('homepage_banner_translations')
    op.drop_table('homepage_banner_cta')
    op.drop_table('homepage_banner')
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_reports():
    pass
