"""empty message

Revision ID: eecc38549f1
Revises: 4c07b9830a2
Create Date: 2015-01-27 11:41:43.917378

"""

# revision identifiers, used by Alembic.
revision = 'eecc38549f1'
down_revision = '4c07b9830a2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_user_id', sa.Integer(), nullable=False),
    sa.Column('user_data', postgresql.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('walkthrough_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_user_id'], ['user_activity.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['walkthrough_id'], ['walkthrough.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'section', sa.Column('campaign_message', sa.Unicode(), nullable=True))
    op.add_column(u'section', sa.Column('cta_button', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def upgrade_reports():
    pass


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'section', 'cta_button')
    op.drop_column(u'section', 'campaign_message')
    op.drop_table('leads')
    ### end Alembic commands ###


def downgrade_reports():
    pass
